spring:
  output: #로그 색상 바꾸기
    ansi:
      enabled: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 521878069403-pe47h04vdr0bceboq7fm9430bahsae13.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "http://jandp-travel.kro.kr:8080/login/oauth2/code/google"

jwt:
  secret: randomTestValueItisNotUsedInProdEnv
  expiration: 180000000000 # 7 years
  #  expiration: 60000 # 1 minutes -> 리프레시 토큰 테스트 시 사용
  refresh:
    expiration: 604800000 # 7 days

admin:
  email: test@gmail.com,test1@gmail.com

google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY}

  server:
    port: 8080

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method #DELETE → GET → PATCH → POST → PUT
    doc-expansion: none

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY} # IAM 엑세스 키
      secretKey: ${AWS_S3_SECRET_KEY} # IAM 시크릿 키
    region:
      static: ap-northeast-2
    s3:
      bucket: jandp-bucket-files # 버킷 이름
    stack:
      auto: false

