spring:
  datasource:
      url: jdbc:postgresql://dpg-d054bn9r0fns73d24a7g-a.singapore-postgres.render.com:5432/jandpdb
      username: jandpuser
      password: 2Z5ck40S29fhkltqKsLPiTfS5SImlrtq
      driver-class-name: org.postgresql.Driver

  jpa:
#    defer-datasource-initialization: true
#    show_sql: true
#    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        auto_quote_keyword: true
        jdbc:
          batch_size: 1000
        order_insert: true
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        use_sql_comments: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 521878069403-pe47h04vdr0bceboq7fm9430bahsae13.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "https://j-p-plan.vercel.app/survey"
