spring:
  h2:
    console:
      enabled: true  # 여기까지만 해도 H2 Browser 생성됨
      path: /h2  # 추가 - Context path 변경
  datasource: # 추가
    url: jdbc:h2:mem:test  # 추가 - JDBC URL 변경
  output: #로그 색상 바꾸기
    ansi:
      enabled: always

  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        auto_quote_keyword: true
        jdbc:
          batch_size: 1000
        order_insert: true
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

jwt:
  secret: randomTestValueItisNotUsedInProdEnv
  expiration: 1800000 # 30 minutes
  #  expiration: 60000 # 1 minutes -> 리프레시 토큰 테스트 시 사용
  refresh:
    expiration: 604800000 # 7 days

admin:
  email: test@gmail.com,test1@gmail.com

google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY}

  server:
    port: 8080

