package com.jp.backend.global.exception;

import lombok.Getter;

@Getter
public enum ExceptionCode {
	NOT_IMPLEMENTED(501, "요청한 기능이 아직 구현되어 있지 않습니다."),
	USER_NONE(404, "USER_NONE"),
	USER_DUPLICATED(409, "USER_DUPLICATED"),
	WIDTH_OR_HEIGHT_REQUIRED(400, "너비 또는 높이 중 하나는 필요합니다."),
	TYPE_NONE(404, "TYPE_NONE"),

	// JWT Token
	TOKEN_INVALID(401, "TOKEN_INVALID"),
	TOKEN_NOT_EXPIRED(400, "TOKEN_NOT_EXPIRED"),
	REFRESH_TOKEN_NOT_FOUND(400, "REFRESH_TOKEN_NOT_FOUND"), REFRESH_TOKEN_INVALID(400, "REFRESH_TOKEN_INVALID"),
	REFRESH_TOKEN_NOT_MATCH(400, "REFRESH_TOKEN_NOT_MATCH"),

	INVALID_ELEMENT(400, "INVALID_ELEMENT"),

	ALREADY_INVITED(409, "ALREADY_INVITED"),

	//Place
	PLACES_API_REQUEST_FAILED(500, "Google Places API 요청 중 오류가 발생하였습니다."),
	PLACE_NONE(404, "PLACE_NONE"),
	PLACE_ID_REQUIRED(400, "PLACE_ID_REQUIRED"),
	TOO_MANY_REQUEST(405, "요청한 개수가 너무 많습니다"),
	PLACE_TYPE_REQUIRED(400, "PLACE_TYPE_REQUIRED"),

	//Review
	REVIEW_NONE(404, "REVIEW_NONE"),
	FORBIDDEN(403, "권한이 없습니다."),

	//Comment
	COMMENT_NONE(404, "COMMENT_NONE"),
	AUTH_FAILED(401, "인증실패"),
	REPLY_NONE(404, "REPLY_NONE"),

	// Like
	ALREADY_LIKED(409, "ALREADY_LIKED"),
	LIKE_NONE(404, "LIKE_NONE"),
	TARGET_NONE(404, "TARGET_NONE"),

	// File
	FILE_NONE(404, "FILE_NONE"),
	FILE_NOT_SUPPORTED(400, "파일 형식이 지원되지 않습니다."),

	//WebSocket
	WEBSOCKET_IO_EXCEPTION(500, "WEBSOCKET_IO_EXCEPTION"),

	//SCHEDULE
	DAY_NONE(404, "DAY_NONE"),
	SCHEDULE_NONE(404, "SCHEDULE_NONE"),
	DAY_LOCATION_NONE(404, "DAY_LOCATION_NONE"),
	SCHEDULE_USER_NONE(404, "해당 일정에 유저가 없습니다."),

	// Diary
	DIARY_NONE(404, "DIARY_NONE"),
	ALREADY_POSTED(409, "ALREADY_POSTED");

	@Getter
	private final int code;

	@Getter
	private final String message;

	ExceptionCode(int code, String message) {
		this.code = code;
		this.message = message;
	}
}
